[settings]
tag = "pipeline"
exchanges = [1, 4, 5]
pathtodata = "../data/exp_raw/PLB_shifted"
t2 = -0.2
fitrange = [2.4, 3.0]
initial_pars = [0.56, -10.7, 0.008]
system = "compass_ηπ"
s2_shift = 0.0
"scale_α" = 0.8
